id = "actionscript"
name = "ActionScript"
description = "ActionScript langauge support"
version = "0.1.1"
schema_version = 1
authors = ["pngdrift"]
repository = "https://github.com/pngdrift/zed-actionscript"

[grammars.actionscript]
repository = "https://github.com/Rileran/tree-sitter-actionscript"
commit = "24919034fc78fdf9bedaac6616b6a60af20ab9b5"

[language_servers.actionscript]
name = "as3mxml"
languages = ["ActionScript"]